export const HT_PROPERTY = 'HT_PROPERTY';
export const HT_PROPERTY_TYPES = 'HT_PROPERTY_TYPES';
export const HT_RENT_DETAILS = 'HT_RENT_DETAILS';
export const HT_TENANT_PROPERTY = 'HT_TENANT_PROPERTY';
